RoR-SampleApp/config/routes.rb
BmnPersonalityApiSkeletonRor::Application.routes.draw do
  scope '(bmn-personality-api-skeleton-ror)' do
    get "home/index"

    match 'all_authors'               =>  'home#all_authors',               :via => :get
    match 'authors_by_personality'    =>  'home#authors_by_personality',    :via => :get
    match 'author'                    =>  'home#author',                    :via => :get
    match 'remove_author'             =>  'home#remove_author',             :via => :get
    match 'add_authors'               =>  'home#add_authors',               :via => :post
    match 'get_author'                =>  'home#get_author',                :via => :get
    match 'get_authors_by_personality' => 'home#get_authors_by_personality', :via => :get
    match 'get_all_authors'           =>  'home#get_all_authors',           :via => :get
    match 'delete_author'             =>  'home#delete_author',             :via => :post

    root :to => 'home#index'

  end
end

RoR-SampleApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

RoR-SampleApp/app/controllers/home_controller.rb
require "net/https"
require "uri"

class HomeController < ApplicationController
  before_filter :http_setup_sling
  def index
  end

  def all_authors


  end

  def authors_by_personality

  end

  def author

  end

  def remove_author

  end

  # NOTE FOR ALL CALLS - HTTP Basic Authentication is required for all calls

  # Makes a call to Personality API -> add_authors, adding authors and their 
  #   personality predictions to your repository of information.
  # Call Type: POST
  # Response format: JSON
  def add_authors
    text = params[:text]
    puts "str:#{text}"
    request = Net::HTTP::Post.new("/personality-api/1/add_authors.json")
    request.basic_auth BmnPersonalityApiSkeletonRor::Application.config.user_name, BmnPersonalityApiSkeletonRor::Application.config.password
    request.set_form_data({ :text => text
                          })
    logger.debug("request #{request}");
    response = @http.request(request)
    render :text => response.body

  end

  # Makes a call to Personality API -> author. Retrieves personality predictions
  #   for an author provided by the request parameter
  # Call Type: GET
  # Response format: JSON
  def get_author
    id = params[:ID]
    puts "ID:#{id}"
    request = Net::HTTP::Get.new("/personality-api/1/author.json?ID=#{id}")
    request.basic_auth BmnPersonalityApiSkeletonRor::Application.config.user_name, BmnPersonalityApiSkeletonRor::Application.config.password
    response = @http.request(request)
    render :text => response.body

  end

  # Makes a call to Personality API -> authors_by_personality. Retrieves personality 
  #   predictions for authors based on a model of personality provided by the user.
  # Call Type: GET
  # Response format: JSON
  def get_authors_by_personality
      count = params[:count] # Optional - and must be an integer. Cuts the amount of authors return down to the number specified.
      timeline = params[:timeline] # Optional - and must be boolean. Determines whether to return personality predictions by day, month, and year.
      traits = params[:traits]
      e = params[:E] # Optional - and must be y, n or o. Extraversion personality trait. 
      s = params[:S] # Optional - and must be y, n or o. Emotional Stability personality trait. 
      a = params[:A] # Optional - and must be y, n or o. Agreeableness personality trait. 
      c = params[:C] # Optional - and must be y, n or o. Conscientiousness personality trait. 
      o = params[:O] # Optional - and must be y, n or o. Openness personality trait. 
      puts "count:#{count}"
      puts "timeline:#{timeline}"
      puts "e:#{e}"
      puts "s:#{s}"
      puts "a:#{a}"
      puts "c:#{c}"
      puts "o:#{o}"

      request = Net::HTTP::Get.new("/personality-api/1/authors_by_personality.json?count=#{count}&timeline=#{timeline}&Extraversion=#{e}&EmotionalStability=#{s}&Agreeableness=#{a}&Conscientiousness=#{c}&Openness=#{o}")
      request.basic_auth BmnPersonalityApiSkeletonRor::Application.config.user_name, BmnPersonalityApiSkeletonRor::Application.config.password
      response = @http.request(request)
      render :text => response.body

  end

  # Makes a call to Personality API -> all_authors. Retrieves personaltiy predictions
  #   for all authors.
  # Call Type: GET
  # Response format: JSON
  def get_all_authors
      count = params[:count] # Optional - and must be an integer. Cuts the amount of authors return down to the number specified.
      timeline = params[:timeline] # Optional - and must be boolean. Determines whether to return personality predictions by day, month, and year.
      traits = params[:traits] # Optional - value must be a substring of "ESACO". Determines which traits to return.
      puts "count:#{count}"
      puts "timeline:#{timeline}"
      puts "traits:#{traits}"

      request = Net::HTTP::Get.new("/personality-api/1/all_authors.json?count=#{count}&timeline=#{timeline}&traits=#{traits}")
      request.basic_auth BmnPersonalityApiSkeletonRor::Application.config.user_name, BmnPersonalityApiSkeletonRor::Application.config.password
      response = @http.request(request)
      render :text => response.body

  end

  # Makes a call to Personality API -> remove_author. Removes an author from your
  #   repository.
  # Call Type: GET
  # Response format: JSON
  def delete_author
      id = params[:ID]
      puts "id:#{id}"
      request = Net::HTTP::Post.new("/personality-api/1/remove_author.json")
      request.basic_auth BmnPersonalityApiSkeletonRor::Application.config.user_name, BmnPersonalityApiSkeletonRor::Application.config.password
      request.set_form_data({ :ID => id
                            })
      logger.debug("request #{request}");
      response = @http.request(request)
      render :text => response.body

    end


  private

  def http_setup_sling
    server = BmnPersonalityApiSkeletonRor::Application.config.sling_server
    uri = URI.parse(server)
    # @http = Net::HTTP.new(uri.host, uri.port)
    @http = Net::HTTP.new(uri.host, uri.port)
    @http.use_ssl = true
    @http.verify_mode = OpenSSL::SSL::VERIFY_NONE
  end
end

RoR-SampleApp/app/helpers/application_helper.rb
module ApplicationHelper
end

RoR-SampleApp/app/helpers/home_helper.rb
module HomeHelper
end

RoR-SampleApp/app/views/home/all_authors.html.erb
<div id="main_div" class="main_div">
    <div id="button_div" class="button_div">
        <div  style="float: right; padding-right: 5px" >
            <input type="button" id="find_button" value="Find" class="button">
        </div>
    </div>
    <div style="clear: both">
    </div>
    <div id="fields_div" class="content_div">
        <div class="content_heading">No. of Authors :</div>
        <div class="content_content"><input type="text" name="count" id="count"> </div>
        <div style="clear: both">
        </div>
        <div class="content_heading">Traits:</div>
        <div class="content_content">
            <input type="checkbox" name="traits"  value="E" checked> Extraversion
            <input type="checkbox" name="traits"  value="S" checked> Emotional Stability
            <input type="checkbox" name="traits"  value="A" checked> Agreeableness
            <input type="checkbox" name="traits"  value="C" checked> Conscientiousness
            <input type="checkbox" name="traits"  value="O" checked> Openness
        </div>
        <div style="clear: both">
        </div>
        <div class="content_heading">TimeLine:</div>
        <div class="content_content">
            <input type="radio" name="timeline" id="timeline"  value="true" > True
            <input type="radio" name="timeline"  value="false" checked="true"> False
        </div>
    </div>

</div>

<script type='text/javascript'>
    $("#find_button").on('click', function() {
        PRA.getAllAuthors();
    });
</script>

RoR-SampleApp/app/views/home/author.html.erb
<div id="main_div" class="main_div">
    <form id="form">
        <div id="button_div" class="button_div">
            <div  style="float: right; padding-right: 5px" >
                <input type="submit" id="find_button" value="Find" class="button">
            </div>
        </div>
        <div style="clear: both">
        </div>
        <div id="fields_div" class="content_div">
            <div class="content_heading">Author ID :</div>
            <div class="content_content"><input type="text" name="author_id" id="author_id" required> </div>
        </div>
    </form>
</div>

<script type='text/javascript'>
    $("#form").submit(function(e) {
        e.preventDefault();
        PRA.getAuthor();
        return false;
    });
</script>

RoR-SampleApp/app/views/home/authors_by_personality.html.erb
<div id="main_div" class="main_div">

    <div id="button_div" class="button_div">
        <div  style="float: right; padding-right: 5px" >
            <input type="button" id="find_button" value="Find" class="button">
        </div>
    </div>
    <div style="clear: both">
    </div>
    <div id="fields_div" class="content_div">
        <div class="content_heading">Extraversion :</div>
        <div class="content_content">
            <input type="radio" name="extraversion"  value="y" > y
            <input type="radio" name="extraversion"  value="n"> n
            <input type="radio" name="extraversion"  value="o" > o
            <input type="radio" name="extraversion"  value="" checked="true"> don't use this trait
        </div>
        <div style="clear: both">
        </div>
        <div class="content_heading">Emotional Stability :</div>
        <div class="content_content">
            <input type="radio" name="emotionalstability"  value="y" > y
            <input type="radio" name="emotionalstability"  value="n"> n
            <input type="radio" name="emotionalstability"  value="o" > o
            <input type="radio" name="emotionalstability"  value="" checked="true"> don't use this trait
        </div>
        <div style="clear: both">
        </div>
        <div class="content_heading">Agreeableness :</div>
        <div class="content_content">
            <input type="radio" name="agreeableness"  value="y" > y
            <input type="radio" name="agreeableness"  value="n"> n
            <input type="radio" name="agreeableness"  value="o" > o
            <input type="radio" name="agreeableness"  value="" checked="true"> don't use this trait
        </div>
        <div style="clear: both">
        </div>
        <div class="content_heading">Conscientiousness :</div>
        <div class="content_content">
            <input type="radio" name="conscientiousness"  value="y" > y
            <input type="radio" name="conscientiousness"  value="n"> n
            <input type="radio" name="conscientiousness"  value="o" > o
            <input type="radio" name="conscientiousness"  value="" checked="true"> don't use this trait
        </div>
        <div style="clear: both">
        </div>
        <div class="content_heading">Openness :</div>
        <div class="content_content">
            <input type="radio" name="openness"  value="y" > y
            <input type="radio" name="openness"  value="n"> n
            <input type="radio" name="openness"  value="o" > o
            <input type="radio" name="openness"  value="" checked="true"> don't use this trait
        </div>
        <div style="clear: both">
        </div>
        <div class="content_heading">Traits:</div>
        <div class="content_content">
            <input type="checkbox" name="traits"  value="E" checked> Extraversion
            <input type="checkbox" name="traits"  value="S" checked> Emotional Stability
            <input type="checkbox" name="traits"  value="A" checked> Agreeableness
            <input type="checkbox" name="traits"  value="C" checked> Conscientiousness
            <input type="checkbox" name="traits"  value="O" checked> Openness
        </div>
        <div style="clear: both">
        </div>
        <div class="content_heading">No. of Authors :</div>
        <div class="content_content"><input type="text" name="count" id="count"> </div>

        <div style="clear: both">
        </div>
        <div class="content_heading">TimeLine:</div>
        <div class="content_content">
            <input type="radio" name="timeline"  value="true" > True
            <input type="radio" name="timeline"  value="false" checked="true"> False
        </div>
    </div>

</div>

<script type='text/javascript'>
    $("#find_button").on('click', function() {
        PRA.getAuthorsByPersonality();
    });
</script>

RoR-SampleApp/app/views/home/index.html.erb
<div id="main_div" class="main_div">
    <form id="form">
        <div id="button_div" class="button_div">
            <div  style="float: right; padding-right: 5px" >
                <input type="button" id="add_button" value="Add Row" class="button">
                <input type="submit" id="submit_button" value="Submit" class="button">
            </div>
        </div>
        <div style="clear: both;">
        </div>
        <div id="fields_div" class="content_div">
            Author : <input type="text" name="author" required>
            Text : <textarea name="text" rows="8" cols="78" required style="vertical-align: baseline; display: inline-block"></textarea>

        </div>
    </form>
</div>

<script type='text/javascript'>
    $("#form").submit(function(e) {
        e.preventDefault();
        PRA.submitData();
        return false;
    });
    $("#add_button").on('click', function() {
        PRA.addRow();
    });
</script>

RoR-SampleApp/app/views/home/remove_author.html.erb
<div id="main_div" class="main_div">
    <form id="form">
        <div id="button_div" class="button_div">
            <div  style="float: right; padding-right: 5px" >
                <input type="submit" id="remove_button" value="remove" class="button">
            </div>
        </div>
        <div style="clear: both; padding: 0;margin: 0;">
        </div>
        <div id="fields_div" class="content_div">
            <div class="content_heading">Author ID :</div>
            <div class="content_content"><input type="text" name="author_id" id="author_id" required> </div>
        </div>
    </form>
</div>
<script type='text/javascript'>
    $("#form").submit(function(e) {
        e.preventDefault();
        PRA.deleteAuthor();
        return false;
    });
</script>

RoR-SampleApp/app/views/layouts/_footer.html.erb
<div id="main_div" class="main_div_footer">
    <div class="content_div_footer">
        Copyright 2013, Behavioral Media Networks
    </div>
</div>

RoR-SampleApp/app/views/layouts/_header.html.erb
<div id="main_div" class="main_div_header">
    <div class="content_div_header">
        <%= image_tag "BMN_logo.png", :id => "bmn_logo", :class => 'bmn_logo'%></br>
        <div class="header_links">
            <%= link_to root_url do %>
                Home
            <% end %>
            &nbsp;&nbsp;&nbsp;
            <%= link_to all_authors_path do %>
                All Authors
            <% end %>
            &nbsp;&nbsp;&nbsp;
            <%= link_to authors_by_personality_path do %>
                Find Authors by Personality
            <% end %>
            &nbsp;&nbsp;&nbsp;
            <%= link_to author_path do %>
                Find Author
            <% end %>
            &nbsp;&nbsp;&nbsp;
            <%= link_to remove_author_path do %>
                Remove Author
            <% end %>
        </div>
    </div>
</div>

RoR-SampleApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height: 100%">
<head>
    <title>ROR client- BMN Personality </title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body style="height: 100%; margin: 0px; padding: 0px">
<div style="height: 100%; margin: 0px; padding: 0px">
    <%= render :partial => 'layouts/header' %>
    <%= yield %>
    <%= render :partial => 'layouts/footer' %>
</div>
</body>
</html>